- name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy function \
        --gen2 \
        --region=REGION_ID \
        --runtime=python312 \
        --entry-point=main \
        --source=./ \
        --trigger-http
