- name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy function --gen2 --runtime=python312 --trigger-http \
          --service-account=project-owner@feedmapping.iam.gserviceaccount.com \
          --region="us-central1" --no-allow-unauthenticated \
          --source=./ --entry-point=hello_get

