name: Freqtrade Hyperopt Matrix

on:
  workflow_dispatch:
    inputs:
      matrix_json:
        description: "Matrix JSON (as string)"
        required: true

jobs:
  run-hyperopt:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        params: ${{ fromJson(inputs.matrix_json).params }}

    env:
      JOBS_ID: 1
      GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4

      - name: ⚙️ Build Maps
        uses: eq19/maps@v8
        id: build-parser
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          chat_id: ${{ secrets.MESSAGE_API }}
          api_key: ${{ secrets.ACCESS_API }}
          api_secret: ${{ secrets.ACCESS_KEY }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          bot_token: ${{ secrets.MONITOR_TOKEN }}
          logs_token: ${{ secrets.WARNING_TOKEN }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
          docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          initiate_pauli_sum: ${{ toJSON(steps.build-parser.outputs) }}

      - name: 🪂 Install freqtrade
        shell: bash
        run: |
          cd ${{ github.workspace }}/user_data/build_helpers && ./install_ta-lib.sh > /dev/null 2>&1
          python -m venv ${{ github.workspace }}/venv && source ${{ github.workspace }}/venv/bin/activate
          pip install -qq --no-cache-dir ta "numpy<3.0" "plotly==6.1.2"
          pip install -qq --no-cache-dir -r ${{ github.workspace }}/user_data/build_helpers/requirements-hyperopt.txt
          pip install -qq --no-cache-dir --no-build-isolation --upgrade freqtrade
          cd ${{ github.workspace }} && cat user_data/config_examples/config_exchange.example.json > user_data/config.json

      - name: 🪂 Download data
        uses: actions/download-artifact@v3
        with:
          name: freqtrade-data
          path: user_data/data/

      - name: 🧠 Run Hyperopt
        env:
          PARAM: ${{ matrix.params }}        
          LOSS: ${{ fromJson(inputs.matrix_json).loss }}
          SPACE: ${{ fromJson(inputs.matrix_json).space }}
        run: |
          echo "Running hyperopt..."
          echo "Loss: $LOSS"
          echo "Space: $SPACE"
          echo "Param: $PARAM"

          # echo -e "\n$hr\nID: $id 👉 Running $hyperopt_loss\nSpaces: $spaces | Days: $days | Epochs: $epochs\n$hr"
          # freqtrade hyperopt --timerange ${start_date}-${end_date} --epochs ${epochs} -j 4 \
          #   --spaces ${spaces} --ignore-missing-spaces --hyperopt-loss ${hyperopt_loss} \
          #   --enable-protections --analyze-per-epoch  --random-state ${id} \
          #   --fee=$FEE --logfile /dev/null > /dev/null 2>&1
